services:
  dev:
    build:
      context: .
      dockerfile: docker/alphabet_mask-dev/Dockerfile
    tty: true
    env_file:
      - ./envfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
    networks:
      - net
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - '.:/home/app/alphabet_mask'
volumes:
  .:
networks:
  net:
